name: $(SourceBranchName)_$(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger:
- master

queue:
  name: Hosted VS2017
steps:
- task: PublishBuildArtifact@0
  displayName: 'Publish Source Code'
  inputs:
    artifactName: MCPW
    pathtoPublish: '$(Build.SourcesDirectory)' 
